In [2]:
train_path='lcqmc/train.tsv'

In [3]:
with open(train_path,'r',encoding='utf-8') as f :
    lines=f.readlines()
    text_a=[]
    text_b=[]
    label=[]
    for i,line in enumerate(lines):
        if i==0:
            continue
        line=line.split('\t')
        text_a.append(line[0])
        text_b.append(line[1])
        label.append(line[2])
print(text_a[0])
print(text_b[0])
print(label[0])


喜欢打篮球的男生喜欢什么样的女生
爱打篮球的男生喜欢什么样的女生
1



In [4]:

model_path=r'C:\Users\wie\Documents\项目\model_file\ernie-1.0'

In [5]:
from transformers import BertModel,BertTokenizer
model=BertModel.from_pretrained(model_path)
tokenizer=BertTokenizer.from_pretrained(model_path)

Some weights of the model checkpoint at C:\Users\wie\Documents\项目\model_file\ernie-1.0 were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [6]:
import jieba

In [49]:
sorted(map(len,text_b),reverse=True)[:10]

[27, 27, 25, 24, 24, 24, 24, 24, 24, 24]

In [50]:
sorted(map(len,text_a),reverse=True)[:10]

[26, 26, 24, 24, 23, 23, 23, 23, 22, 22]

In [100]:
list(jieba.cut(text_a[1]))

['英雄', '联盟', '什么', '英雄', '最好']

In [7]:
encode_a=tokenizer(text_a[1],text_b[1],truncation='longest_first',padding='max_length',max_length=20,return_tensors='pt')
# encode_b=tokenizer(list(jieba.cut(text_b[0])),return_tensors='pt')

In [10]:
encode_a['input_ids'].shape

torch.Size([1, 20])

In [ ]:
encode_a['input_ids'].shape

In [11]:
encode_a['attention_mask'].shape

torch.Size([1, 20])

In [132]:
text_a[1]

'英雄联盟什么英雄最好'

In [133]:
torch.nn.utils.rnn.pad_sequence(text_a,max_length=50,)

{'input_ids': tensor([[   1,  514,  904,  387, 1251,  614,  356,  514,  904,  134,  170,    2]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [134]:
encode_a

{'input_ids': tensor([[   1,  514,  904,  387, 1251,  614,  356,  514,  904,  134,  170,    2]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [135]:
encode_a['input_ids'].shape

torch.Size([1, 12])

In [86]:
encode_a['input_ids']

tensor([[   1, 1022,    2,    0],
        [   1,    9,    2,    0],
        [   1, 1568,    2,    0],
        [   1,  127,    2,    0],
        [   1,   47,  501,    2],
        [   1,   69,  334,    2],
        [   1,    5,    2,    0]])

In [102]:
tokenizer.decode(encode_a['input_ids'][0]).split()

['[CLS]', '英', '雄', '联', '盟', '什', '么', '英', '雄', '最', '好', '[SEP]']

In [106]:
out_a=model(**encode_a)

In [112]:
c,d=out_a

In [113]:
c

'last_hidden_state'

In [110]:
out_a[0]

tensor([[[ 1.5285, -0.1840, -0.5873,  ...,  0.2267, -1.2869,  0.5957],
         [ 0.5399, -0.0453, -0.3098,  ...,  0.5722, -0.2438, -3.7611],
         [ 0.1686, -0.5325, -0.2617,  ...,  0.0855,  0.2366, -2.2502],
         ...,
         [ 0.3396, -0.1772, -0.3614,  ...,  0.4463,  0.5605, -1.2392],
         [ 1.3477, -0.2689, -0.5477,  ...,  0.2529,  0.7380, -0.6643],
         [ 1.5285, -0.1840, -0.5873,  ...,  0.2267, -1.2869,  0.5957]]],
       grad_fn=<NativeLayerNormBackward>)

In [31]:
out_b=model(**encode_b)

In [35]:
out_a.last_hidden_state.shape

torch.Size([1, 18, 768])

In [36]:
out_b.last_hidden_state.shape

torch.Size([1, 17, 768])

In [34]:
import torch.nn.functional as F

In [51]:
import torch

In [123]:
a=torch.rand((5,16,512))
b=torch.randint(0, 20, (5,16,512))

In [124]:
b

tensor([[[12, 14, 14,  ..., 14, 11, 11],
         [ 4, 16, 11,  ...,  3, 18,  7],
         [ 4,  9,  4,  ..., 12, 17,  7],
         ...,
         [ 0, 17,  2,  ...,  7, 16,  4],
         [ 7, 10,  3,  ...,  2, 19, 18],
         [11, 17, 13,  ...,  9, 13,  5]],

        [[ 4, 19, 11,  ..., 14,  9,  0],
         [ 1, 16,  2,  ...,  2, 19, 13],
         [18,  4,  4,  ..., 10, 15,  4],
         ...,
         [16, 14,  2,  ...,  4,  2,  2],
         [ 3,  6, 19,  ...,  6,  9,  7],
         [18,  4,  1,  ...,  3, 19,  8]],

        [[ 3,  8, 16,  ...,  3, 13, 17],
         [14,  2,  2,  ..., 13,  1, 17],
         [11, 14, 11,  ...,  1,  1, 16],
         ...,
         [17,  6,  2,  ...,  8, 11,  3],
         [15,  5,  3,  ..., 16,  9, 12],
         [11, 16,  5,  ...,  7, 11, 18]],

        [[13,  0, 15,  ..., 17,  3, 12],
         [ 4, 16,  0,  ...,  9, 11,  4],
         [17,  1, 19,  ..., 19, 11, 19],
         ...,
         [13,  3, 16,  ...,  7, 11,  6],
         [16,  3, 14,  ..., 17, 16, 

In [126]:
F.cosine_similarity(a,b,dim=-1).shape

torch.Size([5, 16])

In [61]:
l=torch.nn.Linear(10,2)

In [66]:
y=torch.randint(0,2,(5,1))

In [69]:
l(a)

tensor([[-0.7463, -0.0829],
        [-0.5700,  0.0317],
        [-0.4670, -0.0753],
        [-0.6752,  0.1018],
        [-0.5743, -0.1608]], grad_fn=<AddmmBackward>)